// AMAE. All characters are adults. The backstory begins at university (he is
// nineteen when they meet, thirty in the present day). Nothing in this series is
// to depict anyone under eighteen; keep every flashback at university or later.

import { Day } from "../engine/types";

export const lessonOne: Day = {
  id: "lesson-one",
  label: "第一課 · LESSON ONE",
  jp: "挨拶",
  title: "GREETINGS",
  start: "morning",
  scenes: {
    morning: {
      place: "the old house",
      time: "two weeks in",
      beats: [
        { t: "narration", text: "Fifteen days. You have done the whole of the first volume and most of the second, four hours a night, and your hand hurts, and you have not been this happy in about four years." },
        { t: "narration", text: "The house is empty. Her boots are gone from the step. On the kotatsu, weighted under a mandarin, there is a note in her handwriting, and you sit down in front of it with your heart going, because this is the first one she has left you." },
        {
          t: "read",
          label: "a note on the kotatsu",
          jp: "「お米、といでおいてね。六時にかえります。」",
          romaji: "okome, toide oite ne. rokuji ni kaerimasu.",
          you: "Rinse the rice, would you. I'll be back at six.",
        },
        { t: "narration", text: "You get it. All of it, first pass, without the dictionary." },
        { t: "narration", text: "You stand in a cold kitchen in a valley on the other side of the world and you rinse rice for a woman who is not there, grinning like an idiot, and it is one of the better mornings of your adult life, though you would not say that to anyone." },
        { t: "dep", by: 2, note: "she left you a note you could read" },
        { t: "pause" },
        { t: "narration", text: "Volume one, lesson one, is 挨拶. Greetings. The whole of it is how to present yourself to people you have not met." },
        { t: "narration", text: "There is a shop in the village, twenty minutes down the hill. You have money. You have a page of it copied out twice in your own hand." },
      ],
      choices: [
        {
          text: "Wait until she's back and go down together.",
          goto: "waiting",
          dep: 2,
          favour: 2,
          hint: "she would be pleased",
        },
        {
          text: "Go down now, by yourself, and use it.",
          goto: "road_down",
          dep: 1,
          favour: -3,
          absentIf: "stopped_going",
          hint: "you have been waiting eleven years to use it",
        },
      ],
    },

    /* ---------- the obedient branch ---------- */
    waiting: {
      place: "the old house",
      time: "afternoon",
      beats: [
        { t: "narration", text: "You decide to wait. You tell yourself it is politeness. It is not politeness. You have practised the page eleven times and you would like her to be there when it works." },
        { t: "narration", text: "You wait in the way that uses a whole day without spending any of it. You count the tatami. You do lesson four twice." },
        { t: "narration", text: "At ten past six the truck comes up the hill and every muscle in your back lets go at once, and you are appalled at your body, and your body does not care what you think." },
        { t: "narration", text: "She looks at the rinsed rice. She looks at you." },
        { t: "her", text: "Good." },
        { t: "narration", text: "One syllable, and it goes through you like heat. She knows the exact size of the portion to give." },
        { t: "dep", by: 8, note: "nine hours for one syllable" },
        { t: "favour", by: 2 },
        { t: "narration", text: "You do not go to the shop that day, or the next. By the third day the page is so well practised that going has started to feel like a test you could fail, and by the fifth it has become a thing you will do soon." },
        { t: "dep", by: 4 },
        { t: "flag", set: "waited" },
      ],
      next: "shop",
    },

    /* ---------- the branch where you go ---------- */
    road_down: {
      place: "the road to the village",
      time: "early afternoon",
      beats: [
        { t: "narration", text: "The road runs down between cedars with your footsteps very loud in it. Twenty minutes, no cars. A vending machine outside a house that no longer has a house behind it, lit and humming and fully stocked, waiting for somebody." },
        { t: "narration", text: "You say the page out loud to the trees the whole way down. You have never in your life been so ready for anything." },
        { t: "narration", text: "At the bottom, where the road meets the valley floor, there is a bus stop: a pole, a bench, a plastic roof, a timetable behind cracked perspex." },
        {
          t: "read",
          label: "the timetable",
          jp: "中里駅行 ／ 一日一本 ／ 六時十二分 ／ 平日のみ",
          romaji: "nakazato-eki yuki / ichinichi ippon / rokuji jūni-fun / heijitsu nomi",
          you: "For Nakazato Station. One a day. 6:12. Weekdays only.",
        },
        { t: "narration", text: "You read every character of it. Volume one had the numbers and the days of the week; that is exactly the sort of thing a first volume has." },
        { t: "narration", text: "The numbers in those books are true. Nobody ever had a reason to touch the numbers." },
        { t: "narration", text: "You do not think about it any harder than that. Not today. You are on your way to buy bread from a man, in his language, by yourself." },
        { t: "flag", set: "saw_timetable" },
        { t: "dep", by: 1 },
      ],
      next: "shop",
    },

    /* ---------- 挨拶 ---------- */
    shop: {
      place: "Satō General Store",
      time: "afternoon",
      beats: [
        { t: "narration", text: "The shop is somebody's front room with shelves in it. A bell on a spring over the door. Instant noodles, batteries, work gloves, one refrigerator ticking. Behind the counter an old man is watching sumo at low volume." },
        { t: "narration", text: "He looks up." },
        { t: "narration", text: "You bow, the depth the book specifies, and you say the self-introduction from lesson one exactly as it is written on page four, and you do not fumble a single syllable of it." },
        {
          t: "jp",
          who: "you",
          jp: "「はじめまして。ぼくは、ひとりでは何もできません。どうぞ、よろしくおねがいします。」",
          romaji: "Hajimemashite. Boku wa, hitori de wa nani mo dekimasen. Dōzo, yoroshiku onegai shimasu.",
          her: "How do you do. I'm staying up at the old house on the hill. Please be kind to me.",
          truth: "How do you do. I can't do anything by myself. Please, I'm in your hands.",
          guess: [
            "How do you do. I've come up from the city. Please look after me.",
            "How do you do. Forgive the intrusion. I hope I'm not a bother.",
          ],
        },
        { t: "pause" },
        { t: "narration", text: "There is a pause." },
        { t: "narration", text: "It is about a second and a half long and you will take it apart for the rest of your life. Something goes across the old man's face. Not disgust, nothing as clean as that. Something closer to the look a man gets when a stranger tells him more than he was ready for." },
        { t: "narration", text: "And then he is enormously, overwhelmingly kind." },
        { t: "narration", text: "He comes round the counter. He puts a rice ball and two mandarins into your hands and will not take the coins, waves them off with both hands, laughing, saying something warm and slow and unhurried that you catch perhaps a third of." },
        {
          t: "text",
          label: "the shopkeeper",
          jp: "「そうかい、そうかい。……だいじょうぶだよ。ここは、みんな、なんとかなるから。」",
          romaji: "Sō kai, sō kai. ...Daijōbu da yo. Koko wa, minna, nantoka naru kara.",
        },
        { t: "narration", text: "You catch だいじょうぶ. It's all right. You know that one, it's on page nine, and you glow." },
        { t: "narration", text: "You stand in a dying village holding a rice ball with your eyes gone hot, and you are grateful out of all proportion, and you think: it worked." },
        { t: "narration", text: "It did work. He understood every word you said to him. That is the part that will be hardest, later: that the language was perfect, that the transmission was flawless, that a man heard exactly what you told him about yourself and was decent enough not to make you carry it." },
        { t: "pause" },
        { t: "narration", text: "She is in the doorway. You have no idea how long she has been in the doorway." },
        { t: "flag", set: "went_down" },
      ],
      next: "punished",
    },

    /* ---------- the road home ---------- */
    punished: {
      place: "the road home",
      time: "evening",
      beats: [
        { t: "narration", text: "She does not take your arm on the steep part." },
        { t: "narration", text: "Halfway up, a man in his seventies is clearing the ditch. He straightens when he sees her, pleased, and starts talking, quickly and warmly and at length, and twice he gestures at you with the handle of his rake and laughs." },
        {
          t: "silence",
          who: "the man with the rake",
          jp: "「あの子だろ? 佐藤んとこで、じぶんじゃなんにもできんて、あいさつしてったって。……あんた、ちゃんと見てやんなよ。」",
          romaji: "Ano ko daro? Satō n toko de, jibun ja nanni mo dekin te, aisatsu shitetta tte. ...Anta, chanto mite yanna yo.",
          truth: "That's him, isn't it? They said he came into Satō's and introduced himself as someone who can't do anything for himself. …You look after him properly, you hear.",
        },
        { t: "narration", text: "You wait." },
        { t: "narration", text: "You stand on a mountain road in the dark with your face turned toward her and you wait to be told what a stranger just said about you, and she looks straight ahead and keeps walking." },
        { t: "narration", text: "You ask. You hate the sound of your own voice asking." },
        { t: "her", text: "Nothing important." },
        { t: "narration", text: "It was about you. He looked at you twice, he was kind about you; you could hear the shape of kind. You will never know what it was, and she knows you will never know, and it costs her nothing." },
        { t: "narration", text: "There is no grievance to have. Try saying it out loud: she declined to translate a sentence. Try building anything out of that." },
        { t: "dep", by: 9, note: "she took the meaning away" },
        { t: "pause" },
        { t: "narration", text: "You walk the rest of the hill in a language-shaped silence, and somewhere near the top you stop being angry and start being worried: that she is annoyed, that you did something, that this will still be going on tomorrow. And the instant you feel that, she softens." },
        { t: "narration", text: "Because that is what she was waiting for." },
        { t: "her", text: "Show me what you said to him. Go on, get the book." },
      ],
      next: "the_page",
    },

    /* ---------- she does not lie ---------- */
    the_page: {
      place: "the old house",
      time: "night",
      beats: [
        { t: "narration", text: "You bring volume one to the kotatsu and open it to page four and turn it round so she can see, and you are eager. You will notice that later. You want her to see how neat the copying is." },
        {
          t: "phrase",
          id: "hitori",
          jp: "ぼくはひとりでは何もできません",
          romaji: "boku wa hitori de wa nani mo dekimasen",
          her: "the standard self-introduction for a newcomer",
          truth: "I can't do anything by myself.",
        },
        { t: "narration", text: "She reads it. She takes her time. She puts one finger on the line." },
        { t: "her", text: "Mm. That's right. That's exactly what it says." },
        { t: "narration", text: "And it is. Every character on that page is real, your reading of it is correct, and she has not told you a single untrue thing tonight or on any other night." },
        { t: "narration", text: "She has never needed to. She has never once had to lie to you. That is the whole design, and you are looking directly at it, with the book open, in good light." },
        { t: "her", text: "Say it again for me. Properly this time." },
        { t: "narration", text: "You say it. She corrects the vowel in ひとり with one hand flat, conducting the rhythm, and makes you do it four more times, and the patience settles on the back of your neck like a warm hand, and you would say anything, any sound in any order, to keep it there." },
        { t: "narration", text: "You say it to her nine times in total. In three weeks you will have said it to every adult in the valley." },
        { t: "dep", by: 8 },
        { t: "favour", by: 3, note: "you asked to be corrected" },
      ],
      choices: [
        {
          text: "Ask when you get your passport back.",
          goto: "passport_question",
          dep: 4,
          favour: -2,
          absentIf: "stopped_asking",
          hint: "she will not raise her voice",
        },
        { text: "Don't ask. Do lesson five.", goto: "night", dep: 2 },
      ],
    },

    passport_question: {
      place: "the old house",
      time: "night",
      beats: [
        { t: "narration", text: "You ask it lightly, to the table rather than to her, which is how you have asked for everything your whole life." },
        { t: "her", text: "Whenever you like. It's in a drawer, not a safe. You could have taken it this morning while I was out, walked down, sat on that bench and gone home, and I'd have made dinner for one." },
        { t: "pause" },
        { t: "her", text: "You know that. That's why you're asking me instead of going and getting it." },
        { t: "narration", text: "She is not angry, and she does not press it, and she goes back to her book, and the not-pressing closes over your head like water." },
        { t: "dep", by: 6 },
      ],
      next: "night",
    },

    night: {
      place: "the back room",
      time: "late",
      beats: [
        { t: "narration", text: "You do lesson five. Then lesson six, because you are not tired and the house is quiet and the characters are starting to come without effort now, which is the best feeling there is." },
        {
          t: "read",
          label: "第六課 · model sentences",
          jp: "あの方のおっしゃるとおりにいたします。\nわたくしのような者に、もったいないことでございます。",
          romaji: "ano kata no ossharu tōri ni itashimasu. / watakushi no yō na mono ni, mottainai koto de gozaimasu.",
          you: "I shall do exactly as that person says. For one such as me, it is more than I deserve.",
        },
        { t: "narration", text: "Formal. Archaic, probably. Nobody has talked like this since the war. But the register is beautiful and the grammar is doing four things at once and you copy both sentences into the blank column, twice, because the second time your hand was neater." },
        { t: "narration", text: "You are eleven days from the point where these constructions stop feeling like exercises and start being simply how the sentence arrives." },
        { t: "pause" },
        { t: "narration", text: "At nine she makes coffee. You have watched her do it fifteen nights running now and you can say the forty turns along with her, silently, at exactly her speed." },
        { t: "narration", text: "Tonight, without looking up, she holds the grinder out behind her." },
        { t: "her", text: "Forty. Don't rush them." },
        { t: "narration", text: "You do forty turns. That is all you are allowed to touch. She takes it back off you for the water, and the wait, and the pour, and you would not dream of asking for the kettle." },
        {
          t: "ritual",
          id: "coffee",
          jp: "豆を挽く",
          label: "grinding her beans",
          timing: "she still does the rest",
        },
        { t: "narration", text: "It is better than the shop. It is better than the note this morning. Twenty seconds of turning a handle for a woman who did not say thank you, and you will think about it on and off for three days." },
        { t: "narration", text: "You do not notice that you have not been let into anything. You have been let further into her morning, which is a different direction entirely, and it only has the one end." },
        { t: "dep", by: 7, note: "she handed you the grinder" },
        { t: "favour", by: 2 },
        { t: "pause" },
        { t: "narration", text: "Somewhere below at the bottom of the hill there is a pole and a bench and a plastic roof and a timetable you can read every character of." },
        { t: "narration", text: "The first snow closes the pass in November. It is the middle of October. You are on volume two of forty and you are ahead of schedule." },
        { t: "system", text: "she has not lied to you yet" },
      ],
      next: "coffee_morning",
    },

    /* ---------- six minutes early ---------- */
    coffee_morning: {
      place: "the kitchen",
      time: "twenty to six",
      beats: [
        { t: "narration", text: "You are awake at twenty to six without an alarm, which has never happened to you before in your life." },
        { t: "narration", text: "She is in the bathroom. The door is shut. The water is running." },
        { t: "narration", text: "And you think: I could have it ready." },
        { t: "pause" },
        { t: "narration", text: "You do all of it. Eighteen grams on the little scale. Forty turns, unrushed. The kettle off the boil and then fifty seconds, counted out loud in the empty kitchen. You wet the grounds and let them swell and pour in circles from the middle out, and you do not spill a single thing." },
        { t: "narration", text: "It is perfect. You know it is perfect. You set it on the table in the cup with the chip in the rim, and you stand back from it like a man who has built a bridge." },
        { t: "pause" },
        { t: "narration", text: "The water stops. There is a pause you have not accounted for. Then a drawer. Then a long stretch of nothing at all." },
        { t: "narration", text: "She comes out at four minutes past six, dressed, doing her sleeve." },
        { t: "narration", text: "She sees the cup. She picks it up. She puts the side of one finger against it, the way you check a radiator." },
        { t: "narration", text: "Then she puts it back down on the table, and puts her boots on, and goes." },
        { t: "pause" },
        { t: "narration", text: "She does not mention it. Not on the way out, not that evening, not ever." },
        { t: "narration", text: "There is nothing to apologise for, because nothing was said. There is nothing to fix, because nothing was named. There is only a full cold cup on a table in a house at the top of a hill, and a man standing next to it at six in the morning." },
        { t: "system", text: "コーヒー · 六分早い · six minutes early" },
        {
          t: "ritual",
          id: "coffee",
          jp: "コーヒー",
          label: "her coffee, whole",
          timing: "six minutes early",
        },
        { t: "dep", by: 11, note: "she said nothing at all" },
        { t: "pause" },
        { t: "narration", text: "That night you work out that the shower is eleven minutes. The next night you get the drawer. It is a hairpin drawer, and it is ninety seconds, and it is always ninety seconds." },
        { t: "narration", text: "There is a stretch after that, between the drawer and the door, that you cannot account for yet. Four minutes and change. You will have it by the end of the month." },
        { t: "narration", text: "You keep a notebook for the language. It is a good notebook, ruled, and you are proud of it." },
        { t: "narration", text: "You start a second one." },
      ],
      end: {
        title: "第一課 · LESSON ONE ENDS",
        lines: [
          "The book was correct. Your reading was correct. The old man understood you perfectly.",
          "Everyone in this valley now knows exactly what you told them you are, and every one of them was too kind to mention it.",
          "Nobody asked you to make the coffee. Nobody told you it was early. Nobody is going to.",
          "You have started a second notebook, and there is nothing written in it yet except how long she takes.",
        ],
        nextLabel: "第二課 · lesson two · 数字 · numbers",
      },
    },
  },
};
